services:
  jekyll:
    container_name: jekyll-dev
    tty: true
    stdin_open: true
    build: .
    volumes:
      - ./site:/srv/jekyll
    ports:
      - 4000:4000
    working_dir: /srv/jekyll
    command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --watch"